name: Run Playwright Tests

on:
  schedule:
    - cron: '0 2 * * *'  # Every day at 2:00 AM UTC
  workflow_dispatch:       # Optional: allows manual trigger
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: [ '3.11', '3.12' ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install --with-deps

    - name: Run tests (HTML report)
      run: pytest --html=reports/report.html --self-contained-html

    - name: Run tests (Allure report)
      run: pytest --alluredir=allure-results

    - name: Upload HTML Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: reports/report.html

    - name: Upload Allure Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-results
        path: allure-results/
